const TOGGLE_CART_MENU = "TOGGLE_CART_MENU";
const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
const DECREASE_ITEM_QUANTITY = "DECREASE_ITEM_QUANTITY";
const INCREASE_ITEM_QUANTITY = "INCREASE_ITEM_QUANTITY";

export default {
   TOGGLE_CART_MENU,
   ADD_ITEM_TO_CART,
   REMOVE_ITEM_FROM_CART,
   DECREASE_ITEM_QUANTITY,
   INCREASE_ITEM_QUANTITY
};
