const TOGGLE_DRAWER_CART = "TOGGLE_DRAWER_CART";
const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";

export default { TOGGLE_DRAWER_CART, ADD_ITEM_TO_CART, REMOVE_ITEM_FROM_CART };
