const TOGGLE_CART_MENU = "TOGGLE_CART_MENU";
const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";

export default { TOGGLE_CART_MENU, ADD_ITEM_TO_CART, REMOVE_ITEM_FROM_CART };
