const types = {
   SET_CURRENT_USER: "SET_CURRENT_USER",
   EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
   EMAIL_SIGN_IN_SUCCESS: "EMAIL_SIGN_IN_SUCCESS",
   EMAIL_SIGN_IN_FAILURE: "EMAIL_SIGN_IN_FAILURE"
};

export default types;
